//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Photos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Photos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaCommMvc.Web.Resources.Photos", typeof(Photos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photos.
        /// </summary>
        public static string AddPhotos {
            get {
                return ResourceManager.GetString("AddPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an album name.
        /// </summary>
        public static string AlbumNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AlbumNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelUpload {
            get {
                return ResourceManager.GetString("CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PhotosTitle {
            get {
                return ResourceManager.GetString("PhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the photos are beeing processed..
        /// </summary>
        public static string ProcessingUpload {
            get {
                return ResourceManager.GetString("ProcessingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start upload.
        /// </summary>
        public static string StartUpload {
            get {
                return ResourceManager.GetString("StartUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size is 250MB! If you want to upload more, please split it into multiple .zip files..
        /// </summary>
        public static string UploadLimitMessage {
            get {
                return ResourceManager.GetString("UploadLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new photos.
        /// </summary>
        public static string UploadNewPhotos {
            get {
                return ResourceManager.GetString("UploadNewPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photos were successfully uploaded and are now beeing processed..
        /// </summary>
        public static string UploadSuccessfullText {
            get {
                return ResourceManager.GetString("UploadSuccessfullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successfull.
        /// </summary>
        public static string UploadSuccessfullTitle {
            get {
                return ResourceManager.GetString("UploadSuccessfullTitle", resourceCulture);
            }
        }
    }
}
