// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments

using MediaCommMvc.Web.Models.Forums;
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MediaCommMvc.Web.Controllers
{
    public partial class ForumsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ForumsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateTopic()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTopic);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeletePost()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePost);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditPost()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPost);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FirstNewPostInTopic()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FirstNewPostInTopic);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Forum()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Forum);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Topic()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Topic);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Reply()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reply);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ForumsController Actions { get { return MVC.Forums; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Forums";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Forums";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CreateTopic = "CreateTopic";
            public readonly string DeletePost = "DeletePost";
            public readonly string EditPost = "EditPost";
            public readonly string FirstNewPostInTopic = "FirstNewPostInTopic";
            public readonly string Forum = "Forum";
            public readonly string Index = "Index";
            public readonly string Topic = "Topic";
            public readonly string Reply = "Reply";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CreateTopic = "CreateTopic";
            public const string DeletePost = "DeletePost";
            public const string EditPost = "EditPost";
            public const string FirstNewPostInTopic = "FirstNewPostInTopic";
            public const string Forum = "Forum";
            public const string Index = "Index";
            public const string Topic = "Topic";
            public const string Reply = "Reply";
        }


        static readonly ActionParamsClass_CreateTopic s_params_CreateTopic = new ActionParamsClass_CreateTopic();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateTopic CreateTopicParams { get { return s_params_CreateTopic; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateTopic
        {
            public readonly string id = "id";
            public readonly string topic = "topic";
            public readonly string post = "post";
            public readonly string sticky = "sticky";
            public readonly string excludedUsers = "excludedUsers";
        }
        static readonly ActionParamsClass_DeletePost s_params_DeletePost = new ActionParamsClass_DeletePost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeletePost DeletePostParams { get { return s_params_DeletePost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeletePost
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditPost s_params_EditPost = new ActionParamsClass_EditPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditPost EditPostParams { get { return s_params_EditPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditPost
        {
            public readonly string id = "id";
            public readonly string post = "post";
        }
        static readonly ActionParamsClass_FirstNewPostInTopic s_params_FirstNewPostInTopic = new ActionParamsClass_FirstNewPostInTopic();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FirstNewPostInTopic FirstNewPostInTopicParams { get { return s_params_FirstNewPostInTopic; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FirstNewPostInTopic
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Forum s_params_Forum = new ActionParamsClass_Forum();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Forum ForumParams { get { return s_params_Forum; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Forum
        {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Topic s_params_Topic = new ActionParamsClass_Topic();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Topic TopicParams { get { return s_params_Topic; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Topic
        {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Reply s_params_Reply = new ActionParamsClass_Reply();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Reply ReplyParams { get { return s_params_Reply; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Reply
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ApprovalPane = "ApprovalPane";
                public readonly string CreateTopic = "CreateTopic";
                public readonly string EditPost = "EditPost";
                public readonly string Forum = "Forum";
                public readonly string Index = "Index";
                public readonly string Reply = "Reply";
                public readonly string Topic = "Topic";
            }
            public readonly string ApprovalPane = "~/Views/Forums/ApprovalPane.cshtml";
            public readonly string CreateTopic = "~/Views/Forums/CreateTopic.cshtml";
            public readonly string EditPost = "~/Views/Forums/EditPost.cshtml";
            public readonly string Forum = "~/Views/Forums/Forum.cshtml";
            public readonly string Index = "~/Views/Forums/Index.cshtml";
            public readonly string Reply = "~/Views/Forums/Reply.cshtml";
            public readonly string Topic = "~/Views/Forums/Topic.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ForumsController : MediaCommMvc.Web.Controllers.ForumsController
    {
        public T4MVC_ForumsController() : base(Dummy.Instance) { }

        partial void CreateTopicOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult CreateTopic(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTopic);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CreateTopicOverride(callInfo, id);
            return callInfo;
        }

        partial void CreateTopicOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Topic topic, Post post, int id, bool sticky, string excludedUsers);

        public override System.Web.Mvc.ActionResult CreateTopic(Topic topic, Post post, int id, bool sticky, string excludedUsers)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateTopic);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "topic", topic);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "post", post);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sticky", sticky);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "excludedUsers", excludedUsers);
            CreateTopicOverride(callInfo, topic, post, id, sticky, excludedUsers);
            return callInfo;
        }

        partial void DeletePostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DeletePost(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeletePost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeletePostOverride(callInfo, id);
            return callInfo;
        }

        partial void EditPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult EditPost(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditPostOverride(callInfo, id);
            return callInfo;
        }

        partial void EditPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, Post post);

        public override System.Web.Mvc.ActionResult EditPost(int id, Post post)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "post", post);
            EditPostOverride(callInfo, id, post);
            return callInfo;
        }

        partial void FirstNewPostInTopicOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult FirstNewPostInTopic(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FirstNewPostInTopic);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            FirstNewPostInTopicOverride(callInfo, id);
            return callInfo;
        }

        partial void ForumOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int page);

        public override System.Web.Mvc.ActionResult Forum(int id, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Forum);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ForumOverride(callInfo, id, page);
            return callInfo;
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void TopicOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int page);

        public override System.Web.Mvc.ActionResult Topic(int id, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Topic);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            TopicOverride(callInfo, id, page);
            return callInfo;
        }

        partial void ReplyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MediaCommMvc.Web.ViewModels.ReplyViewModel viewModel);

        public override System.Web.Mvc.ActionResult Reply(MediaCommMvc.Web.ViewModels.ReplyViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reply);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ReplyOverride(callInfo, viewModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
